[pytest]
markers =
    smoke: custom marker used for quick sanity-check tests that verify core functionality
    regression: custom marker used for broader tests verifications for recurring bugs previously fixed

addopts= --alluredir=reports/allure_results