name: UI Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://www.saucedemo.com/
      USERNAME: standard_user
      PASSWORD: secret_sauce
      BROWSER: chromium
      HEADLESS: "true"

    steps:
      # 1. Pull repo's code on the runner
      - name: Checkout code
        uses: actions/checkout@v6

      #2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
         python-version: '3.13'

      #3. Install Python dependencies
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt

      #4. Install Playwright browsers + required OS-level libraries
      # name: Ensure browsers are installed
      # run: python -m playwright install --with-deps

      #5. Run test suite, generate a self-contained HTML report
      - name: Run tests
        run: |
         pytest tests/ -v \
          --browser chromium \
          --html=report.html \
          --self-contained-html
        continue-on-error: true   # let the workflow proceed to upload the report even if tests fail
        
        # 6. Upload the HTML report as a downloadable artifact
      - name: Upload HTML report
        if: always()   # upload the report whether tests passed or failed
        uses: actions/upload-artifact@v4
        with:
           name: html-report
           path: report.html
           retention-days: 14